"""ml_assignment_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HssOlSF8hcG3CS5PGgH8HFIBohQvykbR
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json, os

df = pd.DataFrame()
op_list = [f'Dilation SE{i}' for i in range(1,9)] + [f'Erosion SE{i}' for i in range(1,9)]
path_to_file = "/content/IPARC_ChallengeV2/Dataset/CatA_Simple"

for id in range(100):
  with open(f'{path_to_file}/Task{id:03}.json') as f:
    data = json.load(f)
  with open(f'{path_to_file}/Task{id:03}_soln.txt') as file:
    lines = [line.rstrip() for line in file]
  d = [[np.array(data[i]['input']).squeeze(),np.array(data[i]['output']).squeeze()] for i in range(len(data))]
  print(list(np.array(d).squeeze()))
  for op in op_list:
    True
    
    #print(([num for sublist in d for num in sublist] + [op, op in lines]))

list(range(4)) + [True]